SET FORWARD_SLASHED_PREFIX="%PREFIX:\=/%"
SET FORWARD_SLASHED_LIBRARY_PREFIX="%LIBRARY_PREFIX:\=/%"
SET FORWARD_SLASHED_SRC_DIR="%SRC_DIR:\=/%"

SET PY_MAJOR=%PY_VER:~0,1%

REM Visual Studio for Python 2.7 does not provide msbuild or devenv
IF %PY_MAJOR% LEQ 2 SET CMAKE_GENERATOR=NMake Makefiles

MKDIR build
CD build

cmake -LAH -G "%CMAKE_GENERATOR%"^
 -DWITH_EIGEN=ON^
 -DWITH_CUDA=OFF^
 -DWITH_OPENCL=OFF^
 -DWITH_VTK=OFF^
 -DWITH_OPENNI=OFF^
 -DCMAKE_BUILD_TYPE=Release^
 -DBUILD_TESTS=OFF^
 -DBUILD_PERF_TESTS=OFF^
 -DBUILD_DOCS=OFF^
 -DCMAKE_INSTALL_PREFIX="%FORWARD_SLASHED_LIBRARY_PREFIX%"^
 -DEXECUTABLE_OUTPUT_PATH="%FORWARD_SLASHED_LIBRARY_PREFIX%/bin"^
 -DLIBRARY_OUTPUT_PATH="%FORWARD_SLASHED_LIBRARY_PREFIX%/lib"^
 -DPYTHON%PY_MAJOR%_EXECUTABLE="%FORWARD_SLASHED_PREFIX%/python"^
 -DPYTHON_INCLUDE_DIR="%FORWARD_SLASHED_PREFIX%/include"^
 -DPYTHON_PACKAGES_PATH="%FORWARD_SLASHED_PREFIX%/Lib/site-packages/"^
 -DPYTHON_LIBRARY="%FORWARD_SLASHED_PREFIX%/libs/python%PY_VER:.=%.lib"^
 -DPYTHON%PY_MAJOR%_NUMPY_INCLUDE_DIRS="%FORWARD_SLASHED_PREFIX%/Lib/site-packages/numpy/core/include"^
 -DCMAKE_INSTALL_PREFIX="%FORWARD_SLASHED_LIBRARY_PREFIX%"^
 -DOPENCV_EXTRA_MODULES_PATH="../contrib/modules"^
 ..\opencv

IF ERRORLEVEL 1 EXIT 1

cmake --build . --target INSTALL --config Release

IF ERRORLEVEL 1 EXIT 1

IF "%ARCH%" == "64" (
     SET ARCH_DIR=x64
   ) ELSE (
     SET ARCH_DIR=x86
)
robocopy %LIBRARY_PREFIX%\%ARCH_DIR%\vc%VS_MAJOR%\ %LIBRARY_PREFIX%\ *.* /E

IF %ERRORLEVEL% GEQ 8 EXIT 1

RD /S /Q "%LIBRARY_PREFIX%\bin\Release"
RD /S /Q "%LIBRARY_PREFIX%\bin\Debug"
RD /S /Q "%LIBRARY_PREFIX%\x64"
RD /S /Q "%LIBRARY_PREFIX%\x86"

EXIT 0
